#pragma once

#define ONE_KILOBYTE 1024
#define FOUR_KILOBYTES (ONE_KILOBYTE * 4)
#define FOUR_HUNDRED_KILOBYTES (FOUR_KILOBYTES * 100)
#define NUMBER_OF_ARGUMENTS 4
#define DIRECTORY_TO_SERVE_SIZE 256
#define ARRAY_SIZE(x) (sizeof(x) / sizeof(x[0]))
